### ISSUE TITLE
Proper display of the calculated path.

### ISSUE THREAD

**Issue by raultron** [Ideq/TUD_UAV_3D_Pathfinding#16]
The current method for displaying the path is inefficient and slow. I recommend that you use this Vrep API function to make the drawing:

http://www.coppeliarobotics.com/helpFiles/en/apiFunctions.htm#simAddDrawingObject

**Comment by Ideq** [comment]
Yeah, its updated for the bigger map, still needs to be implemented for the smaller one, because the code needs to be in LUA, because this API-functions does not exist in Python. So it needs to be added in a script of an object in the small map(testroom111.ttt)

**Comment by Ideq** [comment]
The drawing object is now used, even for longer paths the simulation is now not slowed down throug the path
