### ISSUE TITLE
Map data into a file

### ISSUE THREAD

**Issue by raultron** [Ideq/TUD_UAV_3D_Pathfinding#4]
The code should be able to store the map generated into a file (maybe a Python Pickle) so the user is able to decide if a new map must be generated or instead use the previously saved map.

The location of the map and the parameter of generate a new map or not should be given as a command line argument to the program.

**Comment by raultron** [comment]
Now I have found this:

The file "arr_0000.npy" contains the mapdata, if you dont wont to run the code for mapgeneration for "testroom.ttt" open this array in spyder und rename it to "arr"

This forces the interaction with the script to a particular tool (spyder), it would be better to have this option as a command line argument and do the unpickle inside the code.

**Comment by Ideq** [comment]
You are right, this is not a good solution, but it was a solution that saved me waiting 30min for the mapdata. Today we started implementing the mapdata-generation in a bit different way, that is alot faster.

Saving the data into a file will be a good solution, we need to check how this works in python.

**Comment by Ideq** [comment]
The Problem i see is that its necessary to rename the scene every time an object is moved or it could happen that a path through an obstacle is generated

**Comment by raultron** [comment]
Yes, but don't move the obstacles, we are assuming a static scene.

**Comment by raultron** [comment]
Take a look to [Pickle](https://wiki.python.org/moin/UsingPickle), spyder uses this in order to save variables as a file. You can use the same.

**Comment by Ideq** [comment]
I used some other function from numpy, to save arrays to ".npy" files, the mapdata is now loaded automaticly from the file, if a file with the name of the scene exists in the Mapdata-folder
