### ISSUE TITLE
newgoal_positon is not defined

### ISSUE THREAD

**Issue by raultron** [Ideq/TUD_UAV_3D_Pathfinding#5]
Running the code in Ubuntu:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 586, in runfile
    execfile(filename, namespace)
  File "/home/racuna/catkin_ws/src/TUD_UAV_3D_Pathfinding/vrep_mapdata_python.py", line 160, in <module>
    came_from, cost_so_far = a_star_search(grid, (0, 0, 0), newgoal_positon)
NameError: name 'newgoal_positon' is not defined

Any ideas?

**Comment by Ideq** [comment]
which branch are you running? the main one? Maybe someone accidentelly change something there

**Comment by Ideq** [comment]
newgoal_position should not be used somewhere in the main branch, its from the divided code branch

**Comment by RENCHEN90** [comment]
it should be working when you run the divided code branch

**Comment by raultron** [comment]
I am using he divided-code branch with Vrep running in Ubuntu Linux.

**Comment by Ideq** [comment]
the version i just uploaded should run easily, if you are using the "testroom111.ttt", maybe the function to get the newgoal_position was commented

**Comment by Ideq** [comment]
solved
